### ISSUE TITLE
Add a feature to mark attendance from csv files

### ISSUE THREAD

**Issue by satyampsoni** [jobic10/student-management-using-django#11]

**Comment by jobic10** [comment]
Thank you for your suggestion to add a feature for marking attendance from CSV files. While I think it's a valuable addition, I'm currently unable to dedicate time to implement this feature. However, I'd welcome and appreciate any contributions from the community. If you're interested, please feel free to raise a pull request, and we can consider merging it into the project. Thanks for your understanding!
