### ISSUE TITLE
Update Attendance says: Error. Please try again

### ISSUE THREAD

**Issue by developer-acc** [jobic10/student-management-using-django#13]
![Capture](https://github.com/jobic10/student-management-using-django/assets/96925396/03068f5a-b776-4def-9202-ca04e8f5e5d1)

### File staff_update_attendance.html (line 184):
            $.ajax({
                url: "{% url 'update_attendance' %}",
                type: 'POST',
                data: {
                    date: attendance_date,
                    student_ids: student_data,
                }
            }).done(function (response) {
                **if (response == 'OK'){** # Why does it check if the response is "OK" if the response is just HTML page
                    alert("Updated")
                }else{
                    alert("Error. Please try again")
                }
                location.reload()

It just returns HTML not 'OK'
<!DOCTYPE html>
<html>

```
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Student Management System</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css ">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    ...
```
The console:
[21/Dec/2023 22:25:28] "POST /get_attendance HTTP/1.1" 200 68
[21/Dec/2023 22:25:29] "POST /staff/attendance/fetch/ HTTP/1.1" 200 62
[21/Dec/2023 22:25:31] "POST /staff/attendance/update/ HTTP/1.1" 200 18118
[21/Dec/2023 22:25:33] "GET /staff/attendance/update/ HTTP/1.1" 200 18118

The pip list:
Package         Version
--------------- ------------
appdirs         1.4.4
asgiref         3.2.10
certifi         2023.11.17
chardet         3.0.4
distlib         0.3.8
dj-database-url 0.5.0
Django          3.1.1
filelock        3.13.1
gunicorn        20.0.4
idna            2.10
mysql-connector 2.2.9
Pillow          10.1.0
pip             23.3.2
psycopg2        2.8.6
pytz            2023.3.post1
requests        2.24.0
setuptools      65.5.0
six             1.16.0
sqlparse        0.4.4
urllib3         1.25.11
virtualenv      20.0.31
whitenoise      5.2.0

**Comment by jobic10** [comment]
Hi Vazno,
Thanks for writing.
I'm unable to reproduce this issue.
Could you confirm if you made any modifications as this is a bit difficult to trace?
Reclone the repository and try again.
I'm really sorry you're going through this and I'm committed to helping you find a solution.
Kindly write back

**Comment by developer-acc** [comment]
`#'django.middleware.csrf.CsrfViewMiddleware'`, I commented this out, from `settings.py`
This: `SECRET_KEY = os.environ.get('MY_SECRET_KEY')` to `SECRET_KEY = "*"`
That's all

**Comment by developer-acc** [comment]
And 
`Pillow==7.2.0` to `Pillow` in `requirements.txt`
