### ISSUE TITLE
Staticfiles Errorr

### ISSUE THREAD

**Issue by jonirulislam** [jobic10/student-management-using-django#5]
HI Jobic,
If i want to deploy this in heroku. When i run
`python manage.py collectstatic`
I get this error.
![image](https://user-images.githubusercontent.com/84953460/121123333-ddd53180-c844-11eb-8a42-361b6eba397a.png)

**Comment by jobic10** [comment]
Hello, to deploy on Heroku...
You could fork this repository and use Heroku to deploy your github link of the forked repo.
You do not need to run `python manage.py collectstatic`.
However, thanks for pointing out the error. 
I would fix this and push to the main repo.

Thank you!
