### ISSUE TITLE
Integrity eror while deleting student / staff

### ISSUE THREAD

**Issue by mortye** [jobic10/student-management-using-django#6]
cannot delete student/staff it throws an django error

`<html><body>
<h1>IntegrityError
       at /student/delete/1</h1>
  <pre class="exception_value">FOREIGN KEY constraint failed</pre>
  

Request Method: | GET
-- | --
http://127.0.0.1:8000/student/delete/1
3.1.1
IntegrityError
FOREIGN KEY constraint failed

</body>
</html>`

**Comment by jobic10** [comment]
Hi, are you sure you `migrate` ?
I tried it from my end, and it works fine!
Perhaps, give steps to reproduce this error from my end.
Thanks, Mortye.

**Comment by jobic10** [comment]
This will be temporarily closed. Kindly re-open if problem persists.
