### ISSUE TITLE
Student view results

### ISSUE THREAD

**Issue by Dannysesi** [jobic10/student-management-using-django#9]
from student profile, student should have access to view their results per subject but that isn't added.
![Screenshot (79)](https://github.com/jobic10/student-management-using-django/assets/116007382/e9fd880f-be7e-4501-9e69-b6ef7e8db146)

**Comment by jobic10** [comment]
Hey,

Thanks for pointing that out! I totally agree that it would be a cool feature to have. Right now, I'm swamped with some other stuff, so I might not get to it right away.

But hey, if you're up for it, feel free to give it a shot and send in a Pull Request! I'd be stoked if you could contribute to the project. No pressure, though. Take your time, and if you have any questions, just hit me up.

Thanks again for bringing this up!
